name: Validate Yaml Files Check

on: 
  push:
  
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate manifests in dir1 and dir2
        uses: makocchi-git/actions-k8s-manifests-validate-kubeval@1.0.0
        with:
          files: k8s-manifests
          token: ${{ secrets.GITHUB_TOKEN }}
