name: k8s manifest checks

on:
  push:

jobs:
  validate_manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Kubernetes Manifests
        uses: codewdhruv/kubeval-validation@v1.1.1
        with:
          directory: '.'
