name: CI for k8s manifest checks

on:
  push:

jobs:
  validate_k8s_manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Kubernetes Manifests
        uses: codewdhruv/kubeval-validation@v1.1.1
        with:
          directory: '.'
          
