# .github/workflows/manifests-validation.yml
name: manifest checks

on: [push]

jobs:
  validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo
      - uses: actions/checkout@v4
      
      - name: validate manifests
        uses: makocchi-git/actions-k8s-manifests-validate-kubeval@1.0.0
        with:
          files: '.'
          token: ${{ secrets.GITHUB_TOKEN }}
